### ISSUE TITLE
Template failure

### ISSUE THREAD

**Issue by berniedurfee-renaissance** [taeefnajib/ficto#1]
The following template throws an error:

```
columns:
  - name: Blood Group
    type: customlist
    datatype: string
    values: ['A+', 'B+', 'AB+', 'O+', 'A-', 'B-', 'AB-', 'O-']
    pos: 1
  - name: Salary
    type: customint
    datatype: int
    start: 10000
    end: 20000
    round: 1000
    pos: 2
```

```
> ficto -d config.yaml -n 10 -f csv
Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.11.3/bin/ficto", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ficto/main.py", line 60, in main
    generate_file(dataconfig=args.dataconfig, numrows=args.numrows, filetype=args.filetype)
  File "/Users/xxx/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ficto/main.py", line 22, in generate_file
    df = create_dataframe(dataconfig, numrows)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ficto/core/generate.py", line 246, in create_dataframe
    data[col_name] = pd.to_numeric(data[col_name], errors="coerce")
                                   ~~~~^^^^^^^^^^
KeyError: 'Salary'
```

**Comment by taeefnajib** [comment]
Hi @berniedurfee-renaissance please try uninstalling v0.0.4 and installing v0.0.8
```
pip uninstall ficto
pip install ficto==0.0.8
```
Hope you could get rid of the error. Let me know if it worked.
